name: '🧩 Feature Request'
description: Ideas for other new features or improvements
labels: [question]
body:
  - type: textarea
    id: background
    attributes:
      label: 'Background'
      description: A clear and concise description of what the problem is. [Ex] I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: 'User Story'
      description: A clear and concise description of what the feature is. [Ex] (As a) manager, (I want to) be able to understand my colleagues progress, (so) I can better report our sucess and failures.
    validations:
      required: true
